version: "3.7"

services:
  nginx:
    build:
      context: nginx
    image: nginx-static:latest
    #environment:
    #  SUID: 1000
    #  STATIC: /static
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1.0"
          memory: 25M
    volumes:
      - static:/static
    ports:
      - "8000:80"

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_NAME=${USER_NAME:-test}
      - USER_PASSWORD=${USER_PASSWORD:-test123}
      - DOCKER_MODS=linuxserver/mods:openssh-server-rsync
    deploy:
      mode: global
      resources:
        limits:
          cpus: "1.0"
          memory: 25M
    volumes:
      - config:/config
      - static:/static
    ports:
      - "${DOCKER_PORT:-2222}:2222"

volumes:
  static:
  config:
