name: Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Override Tags: comma,separated"
        required: false
  release:
    types: [published]

env:
  REGISTRY: "ghcr.io"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Generate Tags"
        id: tags
        uses: smashedr/docker-tags-action@master
        with:
          images: "${{ env.REGISTRY }}/${{ github.repository }}"
          latest: true
          extra: ${{ inputs.tags }}

      - name: "Build and Push"
        uses: docker/build-push-action@v4
        with:
          context: nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
